--Create your own copy of SH schema:

create user CAPSTONE IDENTIFIED BY "AaZZ0r_cle#1";  --creating new user schema
GRANT CONNECT, resource TO CAPSTONE;    --granting permissions to this user
 
ALTER USER CAPSTONE QUOTA UNLIMITED ON DATA;

BEGIN
    ords_admin.enable_schema (
        p_enabled               => TRUE,
        p_schema                => 'CAPSTONE',
        p_url_mapping_type      => 'BASE_PATH',
        p_url_mapping_pattern   => 'capstone', -- this flag says, use 'capstone' in the URIs for CAPSTONE
        p_auto_rest_auth        => TRUE   -- this flag says, don't expose my REST APIs
    );
    COMMIT;
END;
/

--Now the tables??
--First connect to the schema
--getting help from don gepeto:

CREATE TABLE CAPSTONE.USERS (
    USER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY, -- This creates a default id number using SQL's IDENTITY feature
    USERNAME VARCHAR2(100),
    PASSWORD VARCHAR2(100),
    CONSTRAINT users_pk PRIMARY KEY (USER_ID)   --making id the primary key
);

CREATE TABLE CAPSTONE.STOCKS (
    USER_ID NUMBER,
    STOCK VARCHAR2(100),
    QUANT NUMBER,
    CONSTRAINT fk_user
        FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
);

--lets run some tests:
--creating a test user:
INSERT INTO CAPSTONE.USERS (USERNAME, PASSWORD) 
VALUES ('testUser', 'testPass');    --dont forget: in "production" the password should be hashed
commit;

--lets get some stocks for this user:
--remember we dont know the user_id so we have to make a "subquery":
INSERT INTO CAPSTONE.STOCKS (USER_ID, STOCK, QUANT)
VALUES ((SELECT USER_ID FROM CAPSTONE.USERS WHERE USERNAME = 'testUser'), 'AAPL', 11);

INSERT INTO CAPSTONE.STOCKS (USER_ID, STOCK, QUANT)
VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME = 'testUser'), 'MSFT', 22);

INSERT INTO CAPSTONE.STOCKS (USER_ID, STOCK, QUANT)
VALUES ((SELECT USER_ID FROM CAPSTONE.USERS WHERE USERNAME = 'testUser'), 'NVDA', 33);

INSERT INTO CAPSTONE.STOCKS (USER_ID, STOCK, QUANT)
VALUES ((SELECT USER_ID FROM USERS WHERE USERNAME = 'testUser'), 'GOOGL', 44);

INSERT INTO CAPSTONE.STOCKS (USER_ID, STOCK, QUANT)
VALUES ((SELECT USER_ID FROM CAPSTONE.USERS WHERE USERNAME = 'testUser'), 'AMZN', 55);
commit;

--now we need a way to interact from our server:
--Publish MYOWNSHs tables for REST access. This is almost the same as from databases lab1:

BEGIN
    ORDS.ENABLE_OBJECT(p_enabled => TRUE,
                       p_schema => 'CAPSTONE',
                       p_object => 'USERS',
                       p_object_type => 'TABLE',
                       p_object_alias => 'users',
                       p_auto_rest_auth => FALSE);
    commit;
END;
/

BEGIN
    ORDS.ENABLE_OBJECT(p_enabled => TRUE,
                       p_schema => 'CAPSTONE',
                       p_object => 'STOCKS',
                       p_object_type => 'TABLE',
                       p_object_alias => 'stocks',
                       p_auto_rest_auth => FALSE);
    commit;
END;
/